#!/usr/bin/env python3
"""
Fetch weekly average PR cycle time per repository over the past N weeks.

"Cycle time" is measured from pull request creation to close (including merges).
Only PRs whose closed_at falls within the window are included.

Writes output/pr_cycle_time.json — a list of {week, repo, avg_days_to_close}
records consumed by the Grafana time series panel.

Run otel_health.teams first to generate output/teams.json.
"""

import json
import logging
import os
from argparse import ArgumentParser
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

from otel_health.activity import select_repos, week_start
from otel_health.teams import Cache, GitHubClient

GITHUB_API = "https://api.github.com"
DEFAULT_ORG = "open-telemetry"
DEFAULT_WEEKS = 52  # 1 year
DEFAULT_TOP_REPOS = 100

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


def fetch_pr_durations(
    client: GitHubClient, org: str, repo: str, since_dt: datetime
) -> dict[str, list[float]]:
    """
    Return {week_start_date: [duration_days, ...]} for PRs closed in the window.
    Week is determined by the PR's closed_at date.
    """
    weekly: dict[str, list[float]] = defaultdict(list)
    page = 1
    while True:
        data = client.get(
            f"{GITHUB_API}/repos/{org}/{repo}/pulls",
            {
                "state": "closed",
                "sort": "updated",
                "direction": "desc",
                "per_page": 100,
                "page": page,
            },
        )
        if not data:
            break

        for pr in data:
            closed_at_str = pr.get("closed_at")
            if not closed_at_str:
                continue
            closed_at = datetime.fromisoformat(closed_at_str.replace("Z", "+00:00"))
            if closed_at < since_dt:
                continue
            created_at = datetime.fromisoformat(
                pr["created_at"].replace("Z", "+00:00")
            )
            days = (closed_at - created_at).total_seconds() / 86400
            if days > 365:
                continue  # Ignore outliers (stale PRs closed after more than a year)
            weekly[week_start(closed_at)].append(days)

        # Stop when the oldest updated_at on this page is before our window.
        # Since we sort by updated desc, all subsequent pages will be older still,
        # and closed_at <= updated_at so we won't miss any relevant PRs.
        oldest_updated = min(
            datetime.fromisoformat(p["updated_at"].replace("Z", "+00:00"))
            for p in data
        )
        if oldest_updated < since_dt or len(data) < 100:
            break
        page += 1

    return dict(weekly)


def compute_pr_cycle_time(
    teams_path: Path,
    client: GitHubClient,
    org: str,
    weeks: int,
    top_repos: int,
) -> list[dict]:
    """
    Return sorted list of {week, repo, avg_days_to_close} records.
    Only weeks with at least one closed PR are included.
    """
    teams_data = json.loads(teams_path.read_text())
    repo_list = select_repos(teams_data, top_repos)

    since_dt = datetime.now(timezone.utc) - timedelta(weeks=weeks)
    since_dt = since_dt.replace(hour=0, minute=0, second=0, microsecond=0)
    since_str = since_dt.strftime("%Y-%m-%dT%H:%M:%SZ")

    logger.info(
        f"Fetching PR cycle time for {len(repo_list)} repos "
        f"from {since_str[:10]} ({weeks} weeks)"
    )

    records = []
    for i, repo in enumerate(repo_list, 1):
        logger.info(f"[{i:3d}/{len(repo_list)}] {repo}")
        weekly = fetch_pr_durations(client, org, repo, since_dt)
        for week, durations in weekly.items():
            records.append(
                {
                    "week": f"{week}T00:00:00Z",
                    "repo": repo,
                    "avg_days_to_close": round(sum(durations) / len(durations), 1),
                }
            )

    # Sort by (repo, week) so partitionByValues produces frames in alphabetical repo order.
    records.sort(key=lambda r: (r["repo"], r["week"]))
    return records


def main() -> None:
    parser = ArgumentParser(
        description="Fetch weekly PR cycle time and write output/pr_cycle_time.json"
    )
    parser.add_argument("--org", default=DEFAULT_ORG, help="GitHub organization")
    parser.add_argument(
        "--teams-file",
        default="output/teams.json",
        help="Path to teams.json (generated by otel_health.teams)",
    )
    parser.add_argument("--output-dir", default="output", help="Output directory")
    parser.add_argument("--cache-dir", default="cache", help="Cache directory")
    parser.add_argument(
        "--weeks",
        type=int,
        default=DEFAULT_WEEKS,
        help=f"Number of past weeks to collect (default: {DEFAULT_WEEKS})",
    )
    parser.add_argument(
        "--top-repos",
        type=int,
        default=DEFAULT_TOP_REPOS,
        help=f"Repos to include, ranked by total team members (default: {DEFAULT_TOP_REPOS}, 0 = all)",
    )
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise SystemExit("ERROR: GITHUB_TOKEN environment variable is required")

    cache = Cache(Path(args.cache_dir))
    client = GitHubClient(token, cache)

    records = compute_pr_cycle_time(
        Path(args.teams_file), client, args.org, args.weeks, args.top_repos
    )

    out_path = Path(args.output_dir) / "pr_cycle_time.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(records, indent=2))
    logger.info(f"Written: {out_path} ({len(records)} records)")

    repos = sorted({r["repo"] for r in records})
    print(f"\n{'=' * 52}")
    print(f"  PR Cycle Time  —  {args.org}")
    print(f"{'=' * 52}")
    print(f"  Repos tracked: {len(repos)}")
    print(f"  Weeks covered: {args.weeks}")
    print(f"  Total records: {len(records)}")
    print(f"{'=' * 52}")
    print(f"\n  Written to: {out_path}\n")


if __name__ == "__main__":
    main()
